# Generated by Django 3.2.16 on 2023-01-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarioapi', '0003_auto_20230107_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Cadastrado'), (2, 'Faturado'), (3, 'Analise'), (4, 'Envio'), (5, 'Cancelado'), (6, 'Concluido')], default=1, verbose_name='Status Pedido')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioapi.usuario', verbose_name='Usuario')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
