# Generated by Django 3.2.16 on 2023-01-15 13:04

import apiprodutos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiprodutos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Computadores'), (2, 'Games'), (3, 'Impressão'), (4, 'Telefonia e Tablets'), (5, 'Eletroportáteis'), (6, 'Câmeras e Vídeos'), (7, 'Acessórios'), (8, 'Outros')], default=1, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apiprodutos.models.upload_foto),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(),
        ),
    ]
