# Generated by Django 3.2.16 on 2023-01-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cliente', models.BooleanField(verbose_name='Cliente')),
                ('administrador', models.BooleanField(verbose_name='Fornecedor')),
                ('senha', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=20, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado')),
                ('complemento', models.TextField(blank=True, null=True, verbose_name='Complemento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioapi.usuario', verbose_name='Usuario')),
            ],
            options={
                'ordering': ['logradouro'],
            },
        ),
    ]
