# Generated by Django 3.2.16 on 2023-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=100, verbose_name='Logradouro'),
        ),
    ]
