# Generated by Django 3.2.16 on 2023-01-07 21:20

from django.db import migrations, models
import usuarioapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioapi', '0002_alter_endereco_logradouro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='id_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=usuarioapi.models.upload_foto),
        ),
    ]
