# Generated by Django 3.2.16 on 2023-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioapi', '0003_auto_20230107_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='administrador',
            field=models.BooleanField(verbose_name='Admistrador'),
        ),
    ]
