# Generated by Django 3.2.16 on 2023-01-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidoapp', '0001_initial'),
        ('apiprodutos', '0002_auto_20230115_1004'),
        ('itempedidoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidoapp.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiprodutos.produto', verbose_name='Produto'),
        ),
    ]
